version: '3.9'

# Do not run this file directly. Use the ./bin/docker-startup-scripts instead
# We leverage environment variables that must be exported first

services:
  back_end_server:
    build: ./spring-back-end
    image: ${SPRING_DOCKER_IMAGE_NAME_OUTER}:0.0.1
    ports:
      - "8443:8443"
    container_name: ${SPRING_DOCKER_IMAGE_NAME_OUTER}
  front_end_app:
    build:
      context: ./angular-front-end
      args:
        ANGULAR_WORKDIR: ${DEFAULT_ANGULAR_DOCKER_WORKDIR}
    develop:
      watch:
        - action: sync
          path: ./angular-front-end/src/app
          target: /${DEFAULT_ANGULAR_DOCKER_WORKDIR}/src/app
          ignore:
            - ./angular-front-end/node_modules
        - action: rebuild
          path: ./angular-front-end/package.json
    image: ${ANGULAR_DOCKER_IMAGE_NAME_OUTER}:0.0.1
    ports:
      - "4200:4200"
    container_name: ${ANGULAR_DOCKER_IMAGE_NAME_OUTER}
    depends_on:
      - back_end_server