version: '3.9'

# Do not run this file directly. Use the ./bin/docker-startup-scripts instead
# We leverage environment variables that must be exported first

services:
  back_end_server:
    build: ./spring-back-end
    image: ${DEFAULT_SPRING_DOCKER_IMAGE_NAME}:0.0.1
    ports:
      - "8443:8443"
    container_name: ${DEFAULT_SPRING_DOCKER_IMAGE_NAME}
  front_end_app:
    build: ./angular-front-end
    # develop:
      # watch:
      #   - action: sync
      #     path: ./src/app
      #     target: /docker-app/src/app
      #     ignore:
      #       - node_modules
      #   - action: rebuild
      #     path: package.json
    image: ${DEFAULT_ANGULAR_DOCKER_IMAGE_NAME}:0.0.1
    ports:
      - "4200:4200"
    container_name: ${DEFAULT_ANGULAR_DOCKER_IMAGE_NAME}
    depends_on:
      - back_end_server