INSERT INTO roles(name) VALUES('ROLE_FREE_USER') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_SUBSCRIBED_USER') ON CONFLICT DO NOTHING;
INSERT INTO roles(name) VALUES('ROLE_ADMIN') ON CONFLICT DO NOTHING;