version: '3.9'

# Do not run this file directly. Use the ./bin/docker-startup-scripts instead
# We leverage environment variables that must be exported first

services:
  app:
    build: .
    image: ${SPRING_DOCKER_IMAGE_NAME_INNER}:0.0.1
    ports:
      - "8443:8443"
      - "5001:5000" # Maps: local port:docker port
    container_name: ${SPRING_DOCKER_IMAGE_NAME_INNER}
    environment:
      EXAMPLE: "example value"