version: '3.9'

services:
  app:
    build: .
    image: full-stack-auth-repo-spring-back-end:0.0.1
    ports:
      - "8443:8443"
      - "5001:5000" # Maps: local port:docker port
    container_name: full-stack-auth-repo-spring-back-end
    environment:
      EXAMPLE: "example value"