version: '3.9'

# Do not run this file directly. Use the ./bin/docker-startup-scripts instead
# We leverage environment variables that must be exported first

services:
  pjl-application-db:
    image: "postgres" # https://hub.docker.com/_/postgres/
    restart: always
    container_name: ${POSTGRES_DOCKER_IMAGE_NAME_INNER}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DEFAULT_DOCKER_DATABASE_NAME}
      POSTGRES_USER: ${BACKEND_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${BACKEND_DATASOURCE_PASSWORD}
    volumes:
      - /var/tmp/db-data:/tmp # local directory:container directory
  back-end-server:
    build: .
    image: ${SPRING_DOCKER_IMAGE_NAME_INNER}:0.0.1
    ports:
      - "8443:8443"
      - "5001:5000" # Maps: local port:docker port
    container_name: ${SPRING_DOCKER_IMAGE_NAME_INNER}
    environment:
      DEFAULT_DOCKER_DATABASE_NAME: ${DEFAULT_DOCKER_DATABASE_NAME}
      BACKEND_DATASOURCE_USERNAME: ${BACKEND_DATASOURCE_USERNAME}
      BACKEND_DATASOURCE_PASSWORD: ${BACKEND_DATASOURCE_PASSWORD}
      DATABASE_DOCKER_SERVICE_NAME: ${POSTGRES_DOCKER_COMPOSE_SERVICE_NAME}