.DEFAULT_GOAL := build-and-run

# Some `make` shortcut commands
# For more options, run these bin commands directly from your terminal.
# Adding the -h option after each print the help() function

build:
	./bin/startup-scripts/build

build-and-run:
	./bin/startup-scripts/build-and-run

run:
	./bin/startup-scripts/run

