version: '3.9'

# Do not run this file directly. Use the ./bin/docker-startup-scripts instead
# We leverage environment variables that must be exported first

services:
  app:
    build:
      context: .
      args:
        ANGULAR_WORKDIR: ${DEFAULT_ANGULAR_DOCKER_WORKDIR}
    develop:
      watch:
        - action: sync
          path: ./src/app
          target: /${DEFAULT_ANGULAR_DOCKER_WORKDIR}/src/app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    image: ${DEFAULT_ANGULAR_DOCKER_IMAGE_NAME}:0.0.1
    ports:
      - "4200:4200"
    container_name: ${DEFAULT_ANGULAR_DOCKER_IMAGE_NAME}
