.DEFAULT_GOAL := run-local

LOCAL_START_UP_DIR := bin/local-startup-scripts
DOCKER_START_UP_DIR := bin/docker-startup-scripts

run-local:
	./${LOCAL_START_UP_DIR}/run

run-docker:
  ./${DOCKER_START_UP_DIR}/run-as-docker-container
